### ISSUE TITLE
AcceptUrl (Thank You Page) not working 

### ISSUE THREAD

**Issue by stefanliden** [Billmate/opencart-3-billmate-checkout#51]
We have experienced problems that with a purchase made with Billmate Checkout you will not be directed to the correct thank you page (Accept URL)

gz#160796

**Comment by andyjohansson** [comment]
Refactor the callback and accepturl process.

**Comment by andyjohansson** [comment]
Propably related to #50

**Comment by andyjohansson** [comment]
Will be fixed with #66. Closing this issue.
