### ISSUE TITLE
List all the functions which should be handled by OpenCart itself

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/opencart-3-billmate-checkout#54]

**Comment by KFoobar** [comment]
Creating a list for each individual function probably takes too long, so I have compiled what needs to be done in a rough outline.

Some issues need to be fixed as soon as possible to reduce the problems reported for the module, other issues can be fixed later to reduce the need for maintenance and troubleshooting in the long run.

### Admin
- Some files / classes should be moved to a more appropriate namespace (folder).

### Front
- The language files need to be reviewed. There is no one for Swedish, only Danish and English. The Danish is probably the Swedish one, but it has probably not been translated humanly.
- The methods that loads the Billmate Checkout (iframe/js) need to be reviewed and simplified.
- The custom methods used to activate an order needs to be removed in favor for existing ”core” functions.
- Some help functions used by the module can be replaced with existing functions and classes available in OpenCart.
- The module creates its own table for handling shopping carts and sessions, these should be replaced to use the system as intended.
- Some files should be simplified and follow the structure of the system in how different classes are structured. Partly to simplify future maintenance, but also to improve compatibility with other modules that customers may have installed.

**Comment by andyjohansson** [comment]
If we look at #66. How much of this is still relevant once #66 is completed and released @KFoobar?
