### ISSUE TITLE
Logotype displayed on the invoice

### ISSUE THREAD

**Issue by GradedAB** [Billmate/opencart-3-billmate-checkout#63]
Logotype displayed on the invoice - Does not work. It selects default logo?

**Comment by KFoobar** [comment]
@GradedAB From my tests, this feature seems to work. By adding the filename (Logo3.png etc.) found in Billmate Online I was able to switch the logotype. What did you enter in the input field for the logotype?

**Comment by GradedAB** [comment]
I have used IDs as in the past, but i sure will try filenames 😊
If that works then its ok. Will do a test!


Med vänliga hälsningar
Graded.se
Mathias Blomqvist
[http://www.graded.se/mail.jpg]
0224-30204
info@Graded.se<mailto:info@Graded.se>
www.Graded.se<http://www.graded.se/>
Postadress  | Axelsäng 101 | 733 94 Sala |

Från: David Villa ***@***.***>
Skickat: den 29 april 2021 07:40
Till: Billmate/opencart-3-billmate-checkout ***@***.***>
Kopia: Graded AB ***@***.***>; Mention ***@***.***>
Ämne: Re: [Billmate/opencart-3-billmate-checkout] Logotype displayed on the invoice (#63)


@GradedAB<https://github.com/GradedAB> From my tests, this feature seems to work. By adding the filename (Logo3.png etc.) found in Billmate Online I was able to switch the logotype. What did you enter in the input field for the logotype?

**Comment by GradedAB** [comment]
Yes, it works if we use image logo.png format. This issue can be closed. :)
