### ISSUE TITLE
Enhancment of status handling

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/opencart-3-billmate-checkout#68]
## User Story
As a user, I want to set the order status for new orders, not for Billmate statuses in order to be able to set all new orders as one specific order status.

## Background
When we rewrote the setting of order statuses we had the wrong approach. Instead of defining order status per BIllmate status the shop should be able to configure what all new orders should have for status. Otherwise packaging lists and so on will have different order statuses depending on the payment method:
**As an example:**
Two orders come in, one with the payment method invoice and one with Swish. Since the order with the payment method Swish already is activated it will not have the same order status as invoice. Therefor orders can be "lost" and not packaged and delivered.

## Proposed solution
New Orders --> Defined order status by the shop (All new orders from Billmate get this order status)
When we activate the order, we first do an getPaymentinfo and if the order is already activated when don't do an activatePayment call. Let's elaborate on that solution. The important thing is that all new orders get the same order status in OpenCart.

**Comment by KFoobar** [comment]
Fixed
