### ISSUE TITLE
Order total not correct with discount. 

### ISSUE THREAD

**Issue by GradedAB** [Billmate/opencart-3-billmate-checkout#69]
When applying a disscount, the order total does not update correctly. 

![image](https://user-images.githubusercontent.com/82051203/133237560-b3094f73-84e6-4d53-bff6-703194f53ea3.png)

**Comment by KFoobar** [comment]
@GradedAB Adding support for order total extensions from third party can sometimes be a bit problematic depending on how the extension calculates the discount, which means that you may need to adjust the calculation in the checkout adapted to the third party extension.

I have added an option to enable support for third party extensions. This might not work for all extensions, let me know if it works in your case. 

The updated version can be found here:
[https://github.com/Billmate/opencart-3-billmate-checkout/releases/tag/1.3.0B2](https://github.com/Billmate/opencart-3-billmate-checkout/releases/tag/1.3.0B2)

**Comment by KFoobar** [comment]
This should be fixed in 1.3.0B3. Please reopen this issue if the problem remains.
