### ISSUE TITLE
Amounts in API requests must be int

### ISSUE THREAD

**Issue by kalorifri** [Billmate/opencart-3-billmate-checkout#70]
Amounts in API requests must be int and in minor units ( Cent when Dollar)
Issue seems to start in release 1.3.0B1.
It seems to work in 1.2.0.

Suggested solution: see release 1.2.0 and search for "function toCents"

**Comment by KFoobar** [comment]
Please clarify how the issue presents it self and where/when it occurs or provide the steps needed to reproduce the issue.

**Comment by kalorifri** [comment]
amount to pay could look like 3920.0000000000005 in API request.
Do not know how to reproduce, seems like only some articles in store are affected.

Articles aprice, withouttax 
Cart.Total withouttax, tax, withtax are affected.

I assume that just convert to int should be enough.

**Comment by KFoobar** [comment]
Thanks for the clarification. I believe this issue is solved in the latest beta release (# 3). But I will go through the source code and verify that it is truly resolved.
